# Generated by Django 5.0.6 on 2024-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_work_work_company_site_alter_work_work_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(max_length=30)),
                ('degree_start_date', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('degree_end_date', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('degree_institute', models.CharField(max_length=100)),
            ],
        ),
    ]
