# Generated by Django 5.0.6 on 2024-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=30)),
                ('proj_date', models.DateField()),
                ('proj_img', models.ImageField(upload_to='project/')),
            ],
        ),
    ]
