# Generated by Django 5.0.6 on 2024-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_date_from',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_date_to',
            field=models.DateField(default=None),
        ),
    ]
