# Generated by Django 5.0.6 on 2024-06-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_certification_language_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='cert_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='cert_institute',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='cert_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_institute',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_proficiency',
            new_name='proficiency',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='proj_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='proj_img',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='proj_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_date_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_date_to',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discord_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vimeo_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='x_url',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_company_site',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='web_url',
            field=models.URLField(blank=True),
        ),
    ]
